configuration:  
  projectName: notification-service
#Notification Service Port
server:
 port: 8099
   
logging:
 file: Notification.log
 level: INFO

# MongoDB Properties 
spring:
 data:
  mongodb:
   dbuser: masluser
   database: MahaweliDB
   password: g+H1ppDyrXldSwoLBo6c6Q==
   host: localhost
   port: 27017
   maxConnectionsPerHost: 10000
   threadsAllowedToBlockForConnectionMultiplier: 5
   serverSelectionTimeout: 30000
   maxWaitTime: 120000
   connectTimeout: 10000
   socketTimeout: 0
   socketKeepAlive: false
   sslEnabled: false
   sslInvalidHostNameAllowed: false
   alwaysUseMBeans: false 
   heartbeatFrequency: 10000
   minHeartbeatFrequency: 500
   heartbeatConnectTimeout: 20000
   heartbeatSocketTimeout: 20000
   localThreshold: 15
   cursorFinalizerEnabled: true
   
   
eureka:
  instance:
    preferIpAddress: true
    #leaseRenewalIntervalInSeconds: 1
    #leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: false
    #lease:
      #duration: 5

email:
  smtpserver: 192.168.2.6
  smtpport: 465
  emailaddress: forest@lankagate.gov.lk
  emailpassword: qCF+Kbj2CWIc8I/QALG3nw==
  permitpath: /opt/webapps/notification/permit.html
 # permitpath: permit.html
  permitpath1: /opt/webapps/notification/permit1.html
 # permitpath1: permit1.html
  receiptpath: /opt/webapps/notification/receipt.html
 # receiptpath: receipt.html
  bannerpath: /opt/webapps/notification/email-banner.png
 # bannerpath: email-banner.png
  from: MASL
  
schedule:
  time: "* * * * * *"
  
sms:
  uriSms: "w1dCFIkcAA2pSBqMOeV1O8nqqv1f4NjRQgpJ8b29JSc="
  epr: "Z311JUw304Ow0hMBk9oYc+fdzeKdSKSs2U1C2aN0XVX63VNup/vcCyEOBBJXWrCPMw54Q9vY8NpNm971CjjAf4GLfUY7SVhI0bUsoBw0xt75r7F31Hx/P4axNYW3GvUW3hzifzi/Tcc40T/KmczX1w=="
  prefix: "govsms"
  user: "user"
  key: "key"
  userTest: "t+zj9aG9w7Q+NATfc8Pn6g=="
  keyTest: "pZSOnQ+os4Xw9xo8W7eq3A=="
  
notificationService:
      depCode: MASL
